# Generated by Django 5.1.3 on 2024-12-04 15:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Player",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("player_Team", models.CharField(max_length=5)),
                ("player_Name", models.CharField(max_length=30)),
                ("player_Position", models.CharField(max_length=5)),
                ("player_Total_Shots", models.SmallIntegerField()),
                ("player_Goals", models.SmallIntegerField()),
                ("player_Expected_Goals", models.FloatField()),
                ("player_Total_Passes", models.SmallIntegerField()),
                ("player_Assists", models.SmallIntegerField()),
                ("player_Big_Chances_Created", models.SmallIntegerField()),
                ("player_Tackles", models.SmallIntegerField()),
                ("player_Interceptions", models.SmallIntegerField()),
                ("player_Clearances", models.SmallIntegerField()),
                ("player_Saves", models.SmallIntegerField()),
                ("player_High_Claims", models.SmallIntegerField()),
                ("player_Punches", models.SmallIntegerField()),
                ("player_Appearances", models.SmallIntegerField()),
                ("player_Clean_Sheet", models.SmallIntegerField()),
                ("player_Yellow_Cards", models.SmallIntegerField()),
                ("player_Red_Cards", models.SmallIntegerField()),
                (
                    "player_Status",
                    models.CharField(
                        choices=[
                            ("Available", "Available"),
                            ("Injured", "Injured"),
                            ("Suspended", "Suspended"),
                        ],
                        default="Availabe",
                        max_length=20,
                    ),
                ),
                ("player_Rating", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Squad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "squad_Status",
                    models.CharField(
                        choices=[("Saved", "Saved"), ("Not Created", "Not Created")],
                        default="Not Created",
                        max_length=20,
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="FPLapp.player"
                    ),
                ),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="XI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "player_Role",
                    models.CharField(
                        choices=[("Playing", "Playing"), ("Bench", "Bench")],
                        default="Bench",
                        max_length=20,
                    ),
                ),
                ("captain", models.BooleanField(default=False)),
                ("vice_captain", models.BooleanField(default=False)),
                (
                    "xi_Status",
                    models.CharField(
                        choices=[("Saved", "Saved"), ("Not Created", "Not Created")],
                        default="Not Created",
                        max_length=20,
                    ),
                ),
                (
                    "player",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="FPLapp.player"
                    ),
                ),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
